### ISSUE TITLE
Could you please upload the dataset to Google Drive?

### ISSUE THREAD

**Issue by filonenkoa** [Jung-Jun-Uk/insightKface_pytorch#1]
I have tried to download the dataset from the AI Hub, but it says that 내국인만 데이터 신청이 가능합니다 meaning only Koreans can download it. 
감사합니다.

**Comment by junuke** [comment]
I would love to but I can't distribute it because of the copyright on the
use of faces. sorry

2023년 5월 21일 (일) 오전 2:22, Alexander Filonenko ***@***.***>님이
작성:
